name: Validate Capsule

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          jq empty codex/ui_description_snippet.json
          jq empty capsule.manifest.json
      - name: Validate API spec
        run: |
          pip install openapi-spec-validator
          openapi-spec-validator api/memory_threads_api.yaml
